fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "gleb.sinkovskiy@gmail.com"
        sender_name: "Admin"

    registration:
        form:
            type: App\Form\RegistrationType
